{% set version = "0.18.0" %}

package:
  name: modin-packages
  version: {{ version }}

source:
  url: https://github.com/modin-project/modin/archive/refs/tags/{{ version }}.tar.gz
  sha256: 83de0d80afe9bd43a49d319f549e28cd78c9ad37fa4de22935bcdbb9229b9349
  patches:
    # Remove all requirements from setup.py - they should be handled here.
    # The point is to create a "patch failed" conflict when dependencies change
    # in upstream so this doesn't go unnoticed.
    - patches/0001-Remove-dependencies-from-env_hdk.patch
    - patches/0002-Remove-dependencies-from-setup.py.patch

build:
  number: 0
  # noarch disabled because the recipe now has selector for Ray, see below
  # noarch: python
  skip: true  # [py<36]

# the outputs map the modin options on PyPI (see upstream definition
# https://github.com/modin-project/modin/blob/0.10.1/setup.py#L40-L45)
# from "modin[<option>]" to "modin-<option>" as a conda-forge package
outputs:
  - name: modin-all
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - {{ pin_subpackage('modin-dask', exact=True) }}
        # ray does not have OSX builds yet, also windows for py310 disabled, see gh-60
        - {{ pin_subpackage('modin-ray', exact=True) }}           # [not osx and not (win and py>39)]
        # Note: modin-hdk is conda-only, its dependencies were never published on PyPI
        - {{ pin_subpackage('modin-hdk', exact=True) }}           # [linux and py>=38]
        #- {{ pin_subpackage('modin-remote', exact=True) }}       # turned off for now, see below
        #- {{ pin_subpackage('modin-spreadsheet', exact=True) }}  # turned off for now, see below
        #- {{ pin_subpackage('modin-sql', exact=True) }}          # turned off for now, see below
    test:
      imports:
        # dummy test; actual tests are in subpackages
        - modin

  # compatibility with packagename before split into options
  - name: modin
    requirements:
      host:
        - python
      run:
        - python
        # modin needs at least one engine; use dask as it is more light-weight than ray
        - {{ pin_subpackage('modin-dask', exact=True) }}
    test:
      imports:
        - modin
        - modin.pandas

  - name: modin-core
    build:
      script: python -m pip install . --no-deps --ignore-installed -vv
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - packaging
        - pandas ==1.1.5  # [py<38]
        - pandas ==1.5.2  # [py>=38]
        - numpy >=1.18.5
        - fsspec
        - psutil
        - typing_extensions  # [py<38]
    test:
      imports:
        - modin
        - modin.pandas

  - name: modin-dask
    build:
      skip: false  # workaround section to bring back pipelines
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - dask >=2.22.0
        - distributed >=2.22.0
        - pickle5  # [py<38]
    test:
      imports:
        - modin
        - modin.pandas
      commands:
        - python -c "import modin.pandas as pd, modin.config as cfg; cfg.Engine.put('Dask'); df = pd.DataFrame([])"

  - name: modin-ray
    build:
      # There is no Ray in conda-forge for MacOS yet, see conda-forge/ray-packages-feedstock#2, also windows for py310 disabled, see gh-60
      skip: true  # [osx or (win and py>39)]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - ray-default >=1.4.0,<2.1.0
        # aioredis 2.x breaks Ray < 1.6
        # ref: https://github.com/conda-forge/ray-packages-feedstock/issues/38
        - aioredis <2
        - pyarrow >=4.0.1
        # TODO: remove redis dependency pin when GH modin-project/#4398 is resolved
        - redis-py >=3.5.0,<4.0.0
    test:
      imports:
        - modin
        - modin.pandas
      commands:
        - python -c "import modin.pandas as pd, modin.config as cfg; cfg.Engine.put('Ray'); df = pd.DataFrame([])"

  - name: modin-hdk
    build:
      # there is no Hdk on anything but Linux for now
      skip: true  # [not linux or py<38]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - pyarrow =6
        - pyhdk ==0.2
        - s3fs >=2021.8
    test:
      imports:
        - modin
        - modin.pandas
      commands:
        - python -c "import modin.experimental.pandas as pd, modin.config as cfg; cfg.Engine.put('Native'); cfg.StorageFormat.put('Hdk'); df = pd.DataFrame([])"

  - name: modin-sql
    build:
      # Dependencies dfsql, mindsdb_sql are not in conda-forge yet.
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - dfsql >=0.4.2
        - pyparsing <=2.4.7
    test:
      imports:
        # are there more specific imports?!
        - modin

  - name: modin-remote
    build:
      # Dependency rpyc is not in conda-forge yet.
      # Also requires ray-autoscaler which is now absent because
      # its dependencies on conda-forge are too ancient.
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - boto3
        - cloudpickle
        - rpyc ==4.1.5
    test:
      imports:
        # are there more specific imports?!
        - modin

  # TODO: bring https://pypi.org/project/modin-spreadsheet/ to conda-forge
  # as modin-spreadsheet-core, leave modin-spreadsheet to be a subpackage here;
  # see discussion with upstream developers here:
  # https://github.com/conda-forge/modin-feedstock/pull/14/files#r595534632
  - name: modin-spreadsheet
    build:
      # dependency modin-spreadsheet-core is not in conda-forge yet
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - modin-spreadsheet >=0.1.0
    test:
      imports:
        # are there more specific imports?!
        - modin

about:
  home: https://github.com/modin-project/modin
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Speed up your Pandas workflows by changing a single line of code
  doc_url: https://modin.readthedocs.io/
  dev_url: https://github.com/modin-project/modin

extra:
  recipe-maintainers:
    - devin-petersohn
    - h-vetinari
    - vnlitvinov
    - maksimbo1
    - YarShev
    - mvashishtha
  feedstock-name: modin
