{% set version = "0.31.0" %}

package:
  name: modin-packages
  version: {{ version }}

source:
  url: https://github.com/modin-project/modin/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4b89d9251ef0880e7f1668584f50532dda602d18bc852f04dfe39625b0550a6c
  patches:
    # Remove all requirements from setup.py - they should be handled here.
    # The point is to create a "patch failed" conflict when dependencies change
    # in upstream so this doesn't go unnoticed.
    - patches/0001-Remove-dependencies-from-env_hdk.patch
    - patches/0002-Remove-dependencies-from-setup.py.patch

build:
  number: 0

# the outputs map the modin options on PyPI (see upstream definition
# https://github.com/modin-project/modin/blob/0.10.1/setup.py#L40-L45)
# from "modin[<option>]" to "modin-<option>" as a conda-forge package
outputs:
  - name: modin-all
    build:
      noarch: generic
    requirements:
      run:
        # TODO: https://github.com/modin-project/modin/issues/7309 should be fixed first for py312 support
        - python >=3.9,<3.12
        - {{ pin_subpackage('modin-core', exact=True) }}
        - {{ pin_subpackage('modin-dask', exact=True) }}
        - {{ pin_subpackage('modin-mpi', exact=True) }}
        - {{ pin_subpackage('modin-ray', exact=True) }}
        # Note: modin-hdk is conda-only, its dependencies were never published on PyPI
        - {{ pin_subpackage('modin-hdk', exact=True) }}           # [linux or win]
        - __linux  # [linux]
        - __win    # [win]
        - __osx    # [osx]
        #- {{ pin_subpackage('modin-spreadsheet', exact=True) }}  # turned off for now, see below
    test:
      imports:
        # dummy test; actual tests are in subpackages
        - modin

  # compatibility with packagename before split into options
  - name: modin
    build:
      noarch: generic
    requirements:
      run:
        - python >=3.9,<3.12
        # modin needs at least one engine; use dask as it is more light-weight than ray
        - {{ pin_subpackage('modin-dask', exact=True) }}
    test:
      imports:
        - modin
        - modin.pandas

  - name: modin-core
    build:
      script: python -m pip install . --no-deps --ignore-installed -vv
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.9,<3.12
      run:
        - python >=3.9,<3.12
        - packaging >=21.0
        - pandas >=2.2,<2.3
        - numpy >=1.22.4,<2
        - fsspec >=2022.11.0
        - psutil >=5.8.0
    test:
      imports:
        - modin
        - modin.pandas

  - name: modin-dask
    build:
      noarch: generic
    requirements:
      run:
        - python >=3.9,<3.12
        - {{ pin_subpackage('modin-core', exact=True) }}
        - dask >=2.22.0
        - distributed >=2.22.0
    test:
      imports:
        - modin
        - modin.pandas
      commands:
        - python -c "import modin.pandas as pd, modin.config as cfg; cfg.Engine.put('Dask'); df = pd.DataFrame([])"

  - name: modin-ray
    build:
      noarch: generic
    requirements:
      run:
        - python >=3.9,<3.12
        - {{ pin_subpackage('modin-core', exact=True) }}
        # ray==2.5.0 broken: https://github.com/conda-forge/ray-packages-feedstock/issues/100
        - ray-core >=2.1.0,!=2.5.0
        # https://github.com/modin-project/modin/pull/5270#issuecomment-1331172629
        # workaround for https://github.com/conda/conda/issues/11744
        - grpcio!=1.45.*
        - grpcio!=1.46.*
        - pyarrow >=10.0.1
        # the problem is in Ray, due to the breaking change in setuptools: https://github.com/pypa/setuptools/issues/4385
        - setuptools <70.0.0
    test:
      imports:
        - modin
        - modin.pandas
      commands:
        - python -c "import modin.pandas as pd, modin.config as cfg; cfg.Engine.put('Ray'); df = pd.DataFrame([])"

  - name: modin-hdk
    build:
      noarch: generic
      skip: true  # [not (linux or win)]
    requirements:
      run:
        - python >=3.9,<3.12
        - {{ pin_subpackage('modin-core', exact=True) }}
        - pyhdk ==0.9
        - s3fs >=2022.11.0
        # there is no Hdk on anything but Linux and Windows for now
        - __linux   # [linux]
        - __win     # [win]
    test:
      imports:
        - modin
        - modin.pandas
      commands:
        - python -c "import modin.experimental.pandas as pd, modin.config as cfg; cfg.StorageFormat.put('Hdk'); df = pd.DataFrame([])"

  - name: modin-mpi
    build:
      noarch: generic
    requirements:
      run:
        - python >=3.9,<3.12
        - {{ pin_subpackage('modin-core', exact=True) }}
        - unidist-mpi>=0.2.1
    test:
      # TODO: add tests when https://github.com/conda-forge/unidist-packages-feedstock/issues/4 gets fixed
      imports:
        - modin
        - modin.pandas

  # TODO: bring https://pypi.org/project/modin-spreadsheet/ to conda-forge
  # as modin-spreadsheet-core, leave modin-spreadsheet to be a subpackage here;
  # see discussion with upstream developers here:
  # https://github.com/conda-forge/modin-feedstock/pull/14/files#r595534632
  - name: modin-spreadsheet
    build:
      # dependency modin-spreadsheet-core is not in conda-forge yet
      skip: true
      noarch: generic
    requirements:
      run:
        - python >=3.9,<3.12
        - {{ pin_subpackage('modin-core', exact=True) }}
        - modin-spreadsheet >=0.1.0
    test:
      imports:
        # are there more specific imports?!
        - modin

about:
  home: https://github.com/modin-project/modin
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Speed up your Pandas workflows by changing a single line of code
  doc_url: https://modin.readthedocs.io/
  dev_url: https://github.com/modin-project/modin

extra:
  recipe-maintainers:
    - sfc-gh-mvashishtha
    - anmyachev
    - devin-petersohn
    - h-vetinari
    - vnlitvinov
    - maksimbo1
    - YarShev
    - mvashishtha
  feedstock-name: modin
