{% set name = "modin" %}
{% set version = "0.10.1" %}

package:
  name: modin
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21bc61380f1b7e81fbc3c2ff9a829787f56e19b378a7248b3dc360d99cfae9e8

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  # noarch disabled because the recipe now has selector for Ray, see below
  # noarch: python
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pandas ==1.2.3
    - dask >=2.12
    - distributed >=2.12
    # there is no Ray in conda-forge for MacOS yet, see https://github.com/conda-forge/ray-packages-feedstock/issues/2
    - ray-core >=1.0  # [win or linux]

test:
  imports:
    - modin
    - modin.pandas
about:
  home: https://github.com/modin-project/modin
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Speed up your Pandas workflows by changing a single line of code
  doc_url: https://modin.readthedocs.io/
  dev_url: https://github.com/modin-project/modin

extra:
  recipe-maintainers:
    - devin-petersohn
    - h-vetinari
